"""
ComBat batch correction utilities for metabolomics data.

This module provides functionality to:
1. Run ComBat batch correction with appropriate NaN handling
2. Generate diagnostic visualizations (UMAP, Boxplots, RSD distributions)
3. Calculate pre/post correction metrics

Note:
    PCA plotting has been removed as it's handled by inmoose QC.
    UMAP is kept as it provides complementary visualization to PCA.
"""

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')  # Use non-interactive backend for saving plots
import matplotlib.pyplot as plt
import seaborn as sns
import umap.umap_ as umap
from pathlib import Path
from typing import Tuple, Dict, List, Optional

try:
    from inmoose.pycombat import pycombat_norm
    COMBAT_AVAILABLE = True
except ImportError:
    COMBAT_AVAILABLE = False


def run_combat_and_visualize(
    merged_data_path: str,
    merged_batch_path: str,
    output_dir: str = "combat_output",
    random_state: int = 42,
    show_plots: bool = False,
    save_plots: bool = True,
    rsd_xaxis_max: float = 50.0,
) -> Tuple[pd.DataFrame, Dict[str, Dict[str, float]]]:
    """
    Run ComBat batch correction with NaN handling and generate diagnostic visualizations.
    
    This function:
    1. Loads and preprocesses merged data and batch information
    2. Runs ComBat batch correction using pycombat_norm
    3. Calculates pre/post correction metrics (median intensities, CV)
    4. Generates diagnostic plots (UMAP, Boxplot, RSD distributions)
    
    Args:
        merged_data_path: Path to merged_data_for_combat.csv (features x samples)
        merged_batch_path: Path to merged_batch_for_combat.csv (sample metadata)
        output_dir: Directory to save corrected data and plots (default: "combat_output")
        random_state: Random seed for reproducibility (default: 42)
        show_plots: Whether to display plots interactively (default: False)
        save_plots: Whether to save plots to disk (default: True)
        rsd_xaxis_max: Maximum RSD value to show on x-axis of RSD plots (default: 50.0)
            This caps the x-axis to avoid extreme outliers distorting the visualization.
            
    Returns:
        Tuple of:
        - corrected_data: DataFrame with ComBat-corrected data (features x samples)
        - metrics: Dictionary with pre/post correction metrics including:
            - batch1_median, batch2_median: Median intensities per batch
            - median_diff: Absolute difference between batch medians
            - median_cv: Coefficient of variation between batch medians
            
    Raises:
        FileNotFoundError: If input files don't exist
        ValueError: If no common samples between data and batch info
        ValueError: If batch assignments are missing for any samples
        ImportError: If pycombat is not installed (COMBAT_AVAILABLE = False)
    
    Note:
        NaN values are replaced with half the minimum positive value before ComBat,
        which is a best practice for metabolomics data.
        
        PCA plots have been removed as they are generated by inmoose QC.
        UMAP plots are retained as they provide complementary non-linear visualization.
    """
    if not COMBAT_AVAILABLE:
        raise ImportError("pycombat_norm from inmoose is required but not installed")
    
    # --- Setup ---
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # --- Load and preprocess data ---
    data = pd.read_csv(merged_data_path, index_col=0)  # Features x Samples
    
    # Replace NaN with half the minimum positive value (metabolomics best practice)
    min_positive = data[data > 0].min().min()
    small_value = min_positive / 2 if not pd.isna(min_positive) else 1e-10
    data = data.fillna(small_value)
    
    batch_info = pd.read_csv(merged_batch_path)
    
    # Standardize to strings
    data.columns = data.columns.astype(str)
    batch_info['sample_id'] = batch_info['sample_id'].astype(str)
    
    # Check for common samples
    common_samples = list(set(data.columns) & set(batch_info['sample_id']))
    if not common_samples:
        raise ValueError(
            f"No common samples!\n"
            f"Data columns: {set(data.columns)}\n"
            f"Batch sample_ids: {set(batch_info['sample_id'])}"
        )
    
    # Filter to common samples
    data = data[common_samples]
    batch_info = batch_info[batch_info['sample_id'].isin(common_samples)]
    
    # Create batch vector
    batch_dict = dict(zip(batch_info['sample_id'], batch_info['batch']))
    missing_samples = [col for col in data.columns if col not in batch_dict]
    if missing_samples:
        raise ValueError(f"Missing batch assignments for: {missing_samples}")
    batch_vector = np.array([batch_dict[col] for col in data.columns], dtype=int)
    
    # --- Run ComBat ---
    print("Running ComBat...")
    combat_result = pycombat_norm(
        data,
        batch_vector,
        covar_mod=np.zeros((len(batch_vector), 0)),
        ref_batch=None,
        na_cov_action="na.omit"
    )
    corrected_data = pd.DataFrame(combat_result, index=data.index, columns=data.columns)
    corrected_data.to_csv(output_dir / "combat_corrected_data.csv")
    print(f"✓ Saved to {output_dir}/combat_corrected_data.csv")
    
    # --- Calculate metrics ---
    def calculate_metrics(df: pd.DataFrame, batch_vec: np.ndarray) -> Dict[str, float]:
        """
        Calculate batch correction metrics.
        
        Args:
            df: DataFrame with feature data (features x samples)
            batch_vec: Array of batch labels corresponding to samples
            
        Returns:
            Dictionary with median-based metrics for batch comparison
        """
        unique_batches = np.unique(batch_vec)
        if len(unique_batches) < 2:
            return {
                'batch1_median': float(np.nan),
                'batch2_median': float(np.nan),
                'median_diff': float(np.nan),
                'median_cv': float(np.nan),
            }
        
        # Get data for first two batches
        b1 = df.loc[:, batch_vec == unique_batches[0]]
        b2 = df.loc[:, batch_vec == unique_batches[1]]
        m1 = float(np.median(b1.values))
        m2 = float(np.median(b2.values))
        
        return {
            'batch1_median': m1,
            'batch2_median': m2,
            'median_diff': float(abs(m1 - m2)),
            'median_cv': float(np.std([m1, m2]) / np.mean([m1, m2]) * 100) if (m1 + m2) > 0 else float(np.nan),
        }
    
    metrics = {
        'pre_correction': calculate_metrics(data, batch_vector),
        'post_correction': calculate_metrics(corrected_data, batch_vector),
    }
    
    # --- Generate plots ---
    if save_plots:
        _generate_diagnostic_plots(
            data=data,
            corrected_data=corrected_data,
            batch_vector=batch_vector,
            output_dir=output_dir,
            random_state=random_state,
            rsd_xaxis_max=rsd_xaxis_max,
        )
    
    return corrected_data, metrics


def _generate_diagnostic_plots(
    data: pd.DataFrame,
    corrected_data: pd.DataFrame,
    batch_vector: np.ndarray,
    output_dir: Path,
    random_state: int = 42,
    rsd_xaxis_max: float = 50.0,
) -> None:
    """
    Generate diagnostic visualizations for ComBat correction.
    
    Creates the following plots for both pre- and post-correction data:
    - UMAP: Non-linear dimensionality reduction visualization
    - Boxplot: Distribution of mean intensities per sample by batch
    - RSD distributions: For QC groups (QC3, QC4, blauw)
    
    Args:
        data: Original data before correction (features x samples)
        corrected_data: Data after ComBat correction (features x samples)
        batch_vector: Array of batch labels for each sample
        output_dir: Directory to save plots
        random_state: Random seed for UMAP reproducibility
        rsd_xaxis_max: Maximum RSD value for x-axis (default: 50.0)
    """
    unique_batches = np.unique(batch_vector)
    
    for label, df in [("Before ComBat", data), ("After ComBat", corrected_data)]:
        # Ensure no NaN values for visualization
        if df.isna().any().any():
            min_positive = df[df > 0].min().min()
            small_value = min_positive / 2 if not pd.isna(min_positive) else 1e-10
            df = df.fillna(small_value)
        
        suffix = label.lower().replace(" ", "_")
        
        # --- UMAP ---
        # UMAP provides non-linear dimensionality reduction
        emb = umap.UMAP(random_state=random_state).fit_transform(df.T)
        fig, ax = plt.subplots(figsize=(10, 8))
        sns.scatterplot(x=emb[:, 0], y=emb[:, 1], hue=batch_vector, palette='viridis', ax=ax)
        ax.set_title(f"{label} (UMAP)")
        fig.savefig(output_dir / f"{suffix}_umap.png", dpi=300, bbox_inches='tight')
        plt.close(fig)
        
        # --- Boxplot ---
        fig, ax = plt.subplots(figsize=(12, 6))
        sns.boxplot(x=batch_vector, y=df.T.mean(axis=1), palette='viridis', ax=ax, showfliers=False)
        ax.set_title(f"{label} (Boxplot)")
        ax.set_xlabel('Batch')
        ax.set_ylabel('Mean Intensity per Sample')
        
        # Create proper batch labels
        batch_labels = [f"Batch {b}" for b in sorted(unique_batches)]
        ax.set_xticklabels(batch_labels)
        
        fig.savefig(output_dir / f"{suffix}_boxplot.png", dpi=300, bbox_inches='tight')
        plt.close(fig)
        
        # --- RSD for QC groups ---
        qc_groups = {
            "QC3": [col for col in df.columns if "QC3" in col],
            "QC4": [col for col in df.columns if "QC4" in col],
            "blauw": [col for col in df.columns if "blauw" in col],
        }
        
        for group_name, group_samples in qc_groups.items():
            if not group_samples:
                print(f"No samples found for group: {group_name}")
                continue
            
            group_data = df[group_samples]
            group_means = group_data.mean(axis=1)
            group_stds = group_data.std(axis=1)
            rsd = (group_stds / group_means) * 100
            
            # Print RSD summary
            print(f"\n--- {group_name} ({label}) ---")
            print(f"Median RSD: {rsd.median():.2f}%")
            print(f"Mean RSD: {rsd.mean():.2f}%")
            print(f"Features with RSD > 20%: {(rsd > 20).sum()} ({(rsd > 20).mean() * 100:.1f}%)")
            print(f"Features with RSD > 15%: {(rsd > 15).sum()} ({(rsd > 15).mean() * 100:.1f}%)")
            
            # Plot and save RSD distribution with x-axis limits
            plt.figure(figsize=(8, 4))
            sns.histplot(rsd, bins=30, kde=True)
            plt.axvline(15, color='red', linestyle='--', label='RSD = 15%')
            plt.axvline(20, color='orange', linestyle='--', label='RSD = 20%')
            plt.title(f"RSD Distribution for {group_name} ({label})")
            plt.xlabel("RSD (%)")
            plt.ylabel("Number of Features")
            plt.legend()
            plt.grid(True)
            
            # Set x-axis limits to cap at rsd_xaxis_max on either side
            plt.xlim(0, rsd_xaxis_max)
            
            plt.savefig(output_dir / f"{suffix}_{group_name}_rsd_distribution.png", dpi=300, bbox_inches='tight')
            plt.close()


# =============================================================================
# Individual Visualization Functions (for modular use)
# =============================================================================

def plot_umap(
    data: pd.DataFrame,
    batch_vector: np.ndarray,
    output_path: Path,
    title: str = "UMAP",
    random_state: int = 42,
    figsize: Tuple[int, int] = (10, 8),
    dpi: int = 300,
) -> None:
    """
    Generate and save a UMAP plot.
    
    Args:
        data: Feature data (features x samples)
        batch_vector: Batch labels for each sample
        output_path: Path to save the plot
        title: Plot title (default: "UMAP")
        random_state: Random seed for reproducibility (default: 42)
        figsize: Figure size (default: (10, 8))
        dpi: DPI for saved image (default: 300)
    """
    # Handle NaN values
    if data.isna().any().any():
        min_positive = data[data > 0].min().min()
        small_value = min_positive / 2 if not pd.isna(min_positive) else 1e-10
        data = data.fillna(small_value)
    
    emb = umap.UMAP(random_state=random_state).fit_transform(data.T)
    fig, ax = plt.subplots(figsize=figsize)
    sns.scatterplot(x=emb[:, 0], y=emb[:, 1], hue=batch_vector, palette='viridis', ax=ax)
    ax.set_title(title)
    fig.savefig(output_path, dpi=dpi, bbox_inches='tight')
    plt.close(fig)


def plot_boxplot(
    data: pd.DataFrame,
    batch_vector: np.ndarray,
    output_path: Path,
    title: str = "Boxplot",
    figsize: Tuple[int, int] = (12, 6),
    dpi: int = 300,
) -> None:
    """
    Generate and save a boxplot of mean intensities by batch.
    
    Args:
        data: Feature data (features x samples)
        batch_vector: Batch labels for each sample
        output_path: Path to save the plot
        title: Plot title (default: "Boxplot")
        figsize: Figure size (default: (12, 6))
        dpi: DPI for saved image (default: 300)
    """
    unique_batches = np.unique(batch_vector)
    
    fig, ax = plt.subplots(figsize=figsize)
    sns.boxplot(x=batch_vector, y=data.T.mean(axis=1), palette='viridis', ax=ax, showfliers=False)
    ax.set_title(title)
    ax.set_xlabel('Batch')
    ax.set_ylabel('Mean Intensity per Sample')
    batch_labels = [f"Batch {b}" for b in sorted(unique_batches)]
    ax.set_xticklabels(batch_labels)
    fig.savefig(output_path, dpi=dpi, bbox_inches='tight')
    plt.close(fig)


def plot_rsd_distribution(
    data: pd.DataFrame,
    group_samples: List[str],
    output_path: Path,
    title: str = "RSD Distribution",
    xaxis_max: float = 50.0,
    figsize: Tuple[int, int] = (8, 4),
    dpi: int = 300,
) -> None:
    """
    Generate and save an RSD distribution plot for a QC group.
    
    Args:
        data: Feature data (features x samples)
        group_samples: List of sample names belonging to the QC group
        output_path: Path to save the plot
        title: Plot title (default: "RSD Distribution")
        xaxis_max: Maximum RSD value for x-axis (default: 50.0)
        figsize: Figure size (default: (8, 4))
        dpi: DPI for saved image (default: 300)
    """
    if not group_samples:
        return
    
    group_data = data[group_samples]
    group_means = group_data.mean(axis=1)
    group_stds = group_data.std(axis=1)
    rsd = (group_stds / group_means) * 100
    
    plt.figure(figsize=figsize)
    sns.histplot(rsd, bins=30, kde=True)
    plt.axvline(15, color='red', linestyle='--', label='RSD = 15%')
    plt.axvline(20, color='orange', linestyle='--', label='RSD = 20%')
    plt.title(title)
    plt.xlabel("RSD (%)")
    plt.ylabel("Number of Features")
    plt.legend()
    plt.grid(True)
    plt.xlim(0, xaxis_max)
    plt.savefig(output_path, dpi=dpi, bbox_inches='tight')
    plt.close()
