"""
ComBat batch correction utilities for metabolomics data.

This module provides functionality to:
1. Run ComBat batch correction with appropriate NaN handling
2. Generate diagnostic visualizations (UMAP, Boxplots, RSD distributions, PCA)
3. Calculate pre/post correction metrics

Note:
    General PCA plotting is handled by inmoose QC.
    This module includes specific PCA plots for QC4 and blauw QC samples
    to verify they cluster properly after batch correction.
    UMAP is kept as it provides complementary non-linear visualization to PCA.
"""

import logging
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')  # Use non-interactive backend for saving plots
import matplotlib.pyplot as plt
import seaborn as sns
import umap.umap_ as umap
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from pathlib import Path
from typing import Tuple, Dict, List, Optional

try:
    from inmoose.pycombat import pycombat_norm
    COMBAT_AVAILABLE = True
except ImportError:
    COMBAT_AVAILABLE = False

# Configure logging
logger = logging.getLogger(__name__)


def run_combat_and_visualize(
    merged_data_path: str,
    merged_batch_path: str,
    output_dir: str = "combat_output",
    random_state: int = 42,
    show_plots: bool = False,
    save_plots: bool = True,
    rsd_xaxis_max: float = 50.0,
) -> Tuple[pd.DataFrame, Dict[str, Dict[str, float]]]:
    """
    Run ComBat batch correction with NaN handling and generate diagnostic visualizations.
    
    This function:
    1. Loads and preprocesses merged data and batch information
    2. Runs ComBat batch correction using pycombat_norm
    3. Calculates pre/post correction metrics (median intensities, CV)
    4. Generates diagnostic plots (UMAP, Boxplot, RSD distributions)
    
    Args:
        merged_data_path: Path to merged_data_for_combat.csv (features x samples)
        merged_batch_path: Path to merged_batch_for_combat.csv (sample metadata)
        output_dir: Directory to save corrected data and plots (default: "combat_output")
        random_state: Random seed for reproducibility (default: 42)
        show_plots: Whether to display plots interactively (default: False)
        save_plots: Whether to save plots to disk (default: True)
        rsd_xaxis_max: Maximum RSD value to show on x-axis of RSD plots (default: 50.0)
            This caps the x-axis to avoid extreme outliers distorting the visualization.
            
    Returns:
        Tuple of:
        - corrected_data: DataFrame with ComBat-corrected data (features x samples)
        - metrics: Dictionary with pre/post correction metrics including:
            - batch1_median, batch2_median: Median intensities per batch
            - median_diff: Absolute difference between batch medians
            - median_cv: Coefficient of variation between batch medians
            
    Raises:
        FileNotFoundError: If input files don't exist
        ValueError: If no common samples between data and batch info
        ValueError: If batch assignments are missing for any samples
        ImportError: If pycombat is not installed (COMBAT_AVAILABLE = False)
    
    Note:
        NaN values are replaced with half the minimum positive value before ComBat,
        which is a best practice for metabolomics data.
        
        PCA plots have been removed as they are generated by inmoose QC.
        UMAP plots are retained as they provide complementary non-linear visualization.
    """
    if not COMBAT_AVAILABLE:
        raise ImportError("pycombat_norm from inmoose is required but not installed")
    
    # --- Setup ---
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # --- Load and preprocess data ---
    data = pd.read_csv(merged_data_path, index_col=0)  # Features x Samples

    batch_info = pd.read_csv(merged_batch_path)

    # Standardize to strings
    data.columns = data.columns.astype(str)
    batch_info['sample_id'] = batch_info['sample_id'].astype(str)

    # --- Identify QC samples and track feature presence BEFORE gap-filling ---
    # This is CRITICAL: we need to know which features are present in QC samples
    # BEFORE any gap-filling, otherwise we can't distinguish gap-filled from real features
    qc4_samples = [col for col in data.columns if 'QC4' in col]
    blauw_samples = [col for col in data.columns if 'blauw' in col]
    
    # Track feature presence percentage in each QC group (before gap-filling)
    # We'll use this to filter features for RSD calculation and QC PCA
    qc_feature_presence = {}
    for group_name, group_samples in [("QC4", qc4_samples), ("blauw", blauw_samples)]:
        if group_samples:
            group_data_raw = data[group_samples]
            # Calculate percentage of QC samples where each feature is present (non-NaN)
            qc_feature_presence[group_name] = group_data_raw.notna().mean(axis=1)

    # Replace NaN with half the minimum positive value (metabolomics best practice)
    min_positive = data[data > 0].min().min()
    small_value = min_positive / 2 if not pd.isna(min_positive) else 1e-10
    data = data.fillna(small_value)
    
    # Check for common samples
    common_samples = list(set(data.columns) & set(batch_info['sample_id']))
    if not common_samples:
        raise ValueError(
            f"No common samples!\n"
            f"Data columns: {set(data.columns)}\n"
            f"Batch sample_ids: {set(batch_info['sample_id'])}"
        )
    
    # Filter to common samples
    data = data[common_samples]
    batch_info = batch_info[batch_info['sample_id'].isin(common_samples)]
    
    # Create batch vector
    batch_dict = dict(zip(batch_info['sample_id'], batch_info['batch']))
    missing_samples = [col for col in data.columns if col not in batch_dict]
    if missing_samples:
        raise ValueError(f"Missing batch assignments for: {missing_samples}")
    batch_vector = np.array([batch_dict[col] for col in data.columns], dtype=int)
    
    # --- Run ComBat ---
    print("Running ComBat...")
    combat_result = pycombat_norm(
        data,
        batch_vector,
        covar_mod=np.zeros((len(batch_vector), 0)),
        ref_batch=None,
        na_cov_action="na.omit"
    )
    corrected_data = pd.DataFrame(combat_result, index=data.index, columns=data.columns)
    corrected_data.to_csv(output_dir / "combat_corrected_data.csv")
    print(f"✓ Saved to {output_dir}/combat_corrected_data.csv")
    
    # --- Calculate metrics ---
    def calculate_metrics(df: pd.DataFrame, batch_vec: np.ndarray) -> Dict[str, float]:
        """
        Calculate batch correction metrics.
        
        Args:
            df: DataFrame with feature data (features x samples)
            batch_vec: Array of batch labels corresponding to samples
            
        Returns:
            Dictionary with median-based metrics for batch comparison
        """
        unique_batches = np.unique(batch_vec)
        if len(unique_batches) < 2:
            return {
                'batch1_median': float(np.nan),
                'batch2_median': float(np.nan),
                'median_diff': float(np.nan),
                'median_cv': float(np.nan),
            }
        
        # Get data for first two batches
        b1 = df.loc[:, batch_vec == unique_batches[0]]
        b2 = df.loc[:, batch_vec == unique_batches[1]]
        m1 = float(np.median(b1.values))
        m2 = float(np.median(b2.values))
        
        return {
            'batch1_median': m1,
            'batch2_median': m2,
            'median_diff': float(abs(m1 - m2)),
            'median_cv': float(np.std([m1, m2]) / np.mean([m1, m2]) * 100) if (m1 + m2) > 0 else float(np.nan),
        }
    
    metrics = {
        'pre_correction': calculate_metrics(data, batch_vector),
        'post_correction': calculate_metrics(corrected_data, batch_vector),
    }
    
    # --- Generate plots ---
    if save_plots:
        _generate_diagnostic_plots(
            data=data,
            corrected_data=corrected_data,
            batch_vector=batch_vector,
            batch_dict=batch_dict,
            output_dir=output_dir,
            random_state=random_state,
            rsd_xaxis_max=rsd_xaxis_max,
            qc_feature_presence=qc_feature_presence,
        )
    
    return corrected_data, metrics


def _generate_diagnostic_plots(
    data: pd.DataFrame,
    corrected_data: pd.DataFrame,
    batch_vector: np.ndarray,
    batch_dict: Dict[str, int],
    output_dir: Path,
    random_state: int = 42,
    rsd_xaxis_max: float = 50.0,
    qc_feature_presence: Optional[Dict[str, pd.Series]] = None,
) -> None:
    """
    Generate diagnostic visualizations for ComBat correction.
    
    Creates the following plots for both pre- and post-correction data:
    - UMAP: Non-linear dimensionality reduction visualization
    - Boxplot: Distribution of mean intensities per sample by batch
    - RSD distributions: For QC groups (QC4, blauw) with filtering for complete and high-intensity features
    - PCA plot: For ALL samples (showing batch separation) with QC samples highlighted
    - PCA plot: For QC4 and blauw QC samples only to verify clustering
    
    Args:
        data: Original data before correction (features x samples)
        corrected_data: Data after ComBat correction (features x samples)
        batch_vector: Array of batch labels for each sample
        batch_dict: Dictionary mapping sample names to batch labels
        output_dir: Directory to save plots
        random_state: Random seed for UMAP reproducibility
        rsd_xaxis_max: Maximum RSD value for x-axis (default: 50.0)
    """
    unique_batches = np.unique(batch_vector)
    
    for label, df in [("Before ComBat", data), ("After ComBat", corrected_data)]:
        # Ensure no NaN values for visualization
        if df.isna().any().any():
            min_positive = df[df > 0].min().min()
            small_value = min_positive / 2 if not pd.isna(min_positive) else 1e-10
            df = df.fillna(small_value)
        
        # Filter batch_vector to match df columns
        # This is critical: df might have been filtered, so batch_vector must match
        df_samples = df.columns.tolist()
        batch_vector_filtered = np.array([batch_dict[col] for col in df_samples])
        
        suffix = label.lower().replace(" ", "_")
        
        # --- UMAP ---
        # UMAP provides non-linear dimensionality reduction
        emb = umap.UMAP(random_state=random_state).fit_transform(df.T)
        fig, ax = plt.subplots(figsize=(10, 8))
        
        # Convert batch labels to strings to ensure all batches are plotted
        # Seaborn can treat numeric hues as continuous, which may skip values
        batch_labels_str = [f"Batch {b}" for b in batch_vector_filtered]
        
        sns.scatterplot(
            x=emb[:, 0], 
            y=emb[:, 1], 
            hue=batch_labels_str, 
            palette='viridis', 
            ax=ax,
            legend='full'  # Ensure all legend entries are shown
        )
        ax.set_title(f"{label} (UMAP)")
        fig.savefig(output_dir / f"{suffix}_umap.png", dpi=300, bbox_inches='tight')
        plt.close(fig)
        
        # --- Boxplot ---
        fig, ax = plt.subplots(figsize=(12, 6))
        sns.boxplot(x=batch_vector_filtered, y=df.T.mean(axis=1), palette='viridis', ax=ax, showfliers=False)
        ax.set_title(f"{label} (Boxplot)")
        ax.set_xlabel('Batch')
        ax.set_ylabel('Mean Intensity per Sample')
        
        # Create proper batch labels
        batch_labels = [f"Batch {b}" for b in sorted(unique_batches)]
        # Use set_xticks with the unique batch values, then set labels
        unique_batches_sorted = sorted(unique_batches)
        ax.set_xticks(range(len(unique_batches_sorted)))
        ax.set_xticklabels(batch_labels)
        
        fig.savefig(output_dir / f"{suffix}_boxplot.png", dpi=300, bbox_inches='tight')
        plt.close(fig)
        
        # --- RSD for QC groups ---
        qc_groups = {
            "QC4": [col for col in df.columns if "QC4" in col],
            "blauw": [col for col in df.columns if "blauw" in col],
        }
        
        for group_name, group_samples in qc_groups.items():
            if not group_samples:
                print(f"No samples found for group: {group_name}")
                continue
            
            group_data = df[group_samples]
            
            # --- Improved RSD calculation with percentage-based filtering ---
            # Use the pre-computed presence percentages from BEFORE gap-filling
            # This is CRITICAL: prevents gap-filled features from inflating RSD
            
            # Get feature presence percentages for this QC group
            if group_name in qc_feature_presence:
                presence_pct = qc_feature_presence[group_name].reindex(df.index, fill_value=0.0)
            else:
                # Fallback: compute from current data (shouldn't happen)
                presence_pct = group_data.notna().mean(axis=1)
            
            # Define filtering thresholds
            presence_thresholds = [0.80, 0.90, 1.00]  # 80%, 90%, 100%
            
            # Calculate RSD for all features first
            group_means_all = group_data.mean(axis=1)
            group_stds_all = group_data.std(axis=1)
            rsd_all = (group_stds_all / group_means_all) * 100
            
            # Print RSD summaries for different presence thresholds
            print(f"\n--- {group_name} ({label}) ---")
            
            for threshold in presence_thresholds:
                mask = presence_pct >= threshold
                group_data_filtered = group_data[mask]
                
                if len(group_data_filtered) == 0:
                    print(f"\nFEATURES IN >= {int(threshold*100)}% QC SAMPLES: 0 features (skipped)")
                    continue
                
                group_means = group_data_filtered.mean(axis=1)
                group_stds = group_data_filtered.std(axis=1)
                rsd = (group_stds / group_means) * 100
                
                # Also filter by intensity (above median)
                intensity_threshold = group_means.median()
                high_intensity_mask = group_means >= intensity_threshold
                rsd_filtered = rsd[high_intensity_mask]
                
                print(f"\nFEATURES IN >= {int(threshold*100)}% QC SAMPLES ({mask.sum()} features):")
                print(f"  Median RSD: {rsd.median():.2f}%")
                print(f"  Mean RSD: {rsd.mean():.2f}%")
                print(f"  Features with RSD > 20%: {(rsd > 20).sum()} ({(rsd > 20).mean() * 100:.1f}%)")
                print(f"  Features with RSD > 15%: {(rsd > 15).sum()} ({(rsd > 15).mean() * 100:.1f}%)")
                
                print(f"  HIGH INTENSITY + >= {int(threshold*100)}% PRESENT ({high_intensity_mask.sum()} features):")
                print(f"    Median RSD: {rsd_filtered.median():.2f}%")
                print(f"    Mean RSD: {rsd_filtered.mean():.2f}%")
                print(f"    Features with RSD > 20%: {(rsd_filtered > 20).sum()} ({(rsd_filtered > 20).mean() * 100:.1f}%)")
                print(f"    Features with RSD > 15%: {(rsd_filtered > 15).sum()} ({(rsd_filtered > 15).mean() * 100:.1f}%)")
            
            # Also print ALL features RSD for comparison
            print(f"\nALL FEATURES (including incomplete, {len(rsd_all)} features):")
            print(f"  Median RSD: {rsd_all.median():.2f}%")
            print(f"  Mean RSD: {rsd_all.mean():.2f}%")
            print(f"  Features with RSD > 20%: {(rsd_all > 20).sum()} ({(rsd_all > 20).mean() * 100:.1f}%)")
            print(f"  Features with RSD > 15%: {(rsd_all > 15).sum()} ({(rsd_all > 15).mean() * 100:.1f}%)")
            
            # For plotting, use 80% threshold + high intensity
            presence_80_mask = presence_pct >= 0.80
            group_data_80 = group_data[presence_80_mask]
            if len(group_data_80) > 0:
                group_means_80 = group_data_80.mean(axis=1)
                intensity_threshold_80 = group_means_80.median()
                high_intensity_mask_80 = group_means_80 >= intensity_threshold_80
                rsd_for_plot = rsd[presence_80_mask][high_intensity_mask_80]
            else:
                rsd_for_plot = rsd
            
            # Plot and save RSD distribution with x-axis limits (using 80% presence + high intensity)
            plt.figure(figsize=(8, 4))
            
            # Filter RSD values for plotting (keep within x-axis range for better visualization)
            rsd_for_plot_filtered = rsd_for_plot[rsd_for_plot <= rsd_xaxis_max]
            num_outliers = (rsd_for_plot > rsd_xaxis_max).sum()
            
            if len(rsd_for_plot_filtered) == 0:
                # All values are outliers, adjust the filter
                rsd_for_plot_filtered = rsd_for_plot
                logger.warning(f"All filtered RSD values exceed {rsd_xaxis_max}% for {group_name} ({label}). Showing all filtered data.")
            elif num_outliers > 0:
                logger.info(f"Filtered out {num_outliers} RSD outliers > {rsd_xaxis_max}% for {group_name} ({label})")
            
            # Use adaptive binning: more bins for smaller ranges, fewer for larger
            data_range = rsd_for_plot_filtered.max() - rsd_for_plot_filtered.min()
            if data_range > 0:
                num_bins = min(30, max(10, int(data_range * 2)))
            else:
                num_bins = 10
            
            sns.histplot(rsd_for_plot_filtered, bins=num_bins, kde=True)
            plt.axvline(15, color='red', linestyle='--', label='RSD = 15%')
            plt.axvline(20, color='orange', linestyle='--', label='RSD = 20%')
            plt.title(f"RSD Distribution for {group_name} ({label})\n(>=80% QC samples + High Intensity)")
            plt.xlabel("RSD (%)")
            plt.ylabel("Number of Features")
            plt.legend()
            plt.grid(True)
            
            # Set x-axis limits
            plt.xlim(0, rsd_xaxis_max)
            
            plt.savefig(output_dir / f"{suffix}_{group_name}_rsd_distribution.png", dpi=300, bbox_inches='tight')
            plt.close()
    
        # --- PCA for ALL samples (both before and after) ---
        # Plot PCA for all samples to show batch separation before/after correction
        fig, ax = plt.subplots(figsize=(12, 10))
        
        # Standardize the data (important for PCA)
        scaler = StandardScaler()
        df_scaled = scaler.fit_transform(df.T)
        
        # Perform PCA
        pca = PCA(n_components=2, random_state=42)
        pca_result = pca.fit_transform(df_scaled)
        
        # Get batch labels for all samples
        all_batch_labels = [batch_dict.get(col, 'Unknown') for col in df.columns]
        
        # Create color palette based on unique batches
        unique_batches_all = sorted(set(all_batch_labels))
        palette_all = sns.color_palette('viridis', n_colors=len(unique_batches_all))
        batch_to_color_all = {b: palette_all[i] for i, b in enumerate(unique_batches_all)}
        colors_all = [batch_to_color_all.get(b, 'gray') for b in all_batch_labels]
        
        # Identify QC samples by type for different markers (excluding QC3)
        qc4_samples = [col for col in df.columns if 'QC4' in col]
        blauw_samples = [col for col in df.columns if 'blauw' in col]
        
        # Get indices for all QC samples
        qc4_indices = [list(df.columns).index(col) for col in qc4_samples] if qc4_samples else []
        blauw_indices = [list(df.columns).index(col) for col in blauw_samples] if blauw_samples else []
        all_qc_indices = qc4_indices + blauw_indices
        
        # Scatter plot for all NON-QC samples (batch colored circles)
        non_qc_indices = [i for i in range(len(df.columns)) if i not in all_qc_indices]
        if non_qc_indices:
            ax.scatter(
                pca_result[non_qc_indices, 0],
                pca_result[non_qc_indices, 1],
                c=[colors_all[i] for i in non_qc_indices],
                alpha=0.6,
                s=40,
                marker='o',
                label='Biological Samples'
            )
        
        # Scatter plot for QC samples with distinct markers and BRIGHT colors
        # QC4: bright blue triangles, blauw: bright yellow diamonds
        if qc4_indices:
            ax.scatter(
                pca_result[qc4_indices, 0],
                pca_result[qc4_indices, 1],
                c='blue',
                alpha=1.0,
                s=80,
                marker='^',
                edgecolors='black',
                linewidth=0.5,
                label='QC4'
            )
        
        if blauw_indices:
            ax.scatter(
                pca_result[blauw_indices, 0],
                pca_result[blauw_indices, 1],
                c='gold',
                alpha=1.0,
                s=80,
                marker='D',
                edgecolors='black',
                linewidth=0.5,
                label='blauw QC'
            )
        
        # Calculate explained variance
        explained_variance = pca.explained_variance_ratio_
        
        ax.set_title(f"{label} (PCA - All Samples)\nExplained Variance: PC1={explained_variance[0]:.2%}, PC2={explained_variance[1]:.2%}")
        ax.set_xlabel(f"PC1 ({explained_variance[0]:.1%})")
        ax.set_ylabel(f"PC2 ({explained_variance[1]:.1%})")
        ax.grid(True, alpha=0.3)
        
        # Create legend for batches and QC types
        from matplotlib.patches import Patch
        from matplotlib.lines import Line2D
        
        legend_elements = [
            Patch(facecolor=batch_to_color_all[b], label=f"Batch {b}")
            for b in sorted(unique_batches_all)
        ]
        
        # Add markers for sample types with their actual colors
        legend_elements.append(Line2D([0], [0], marker='o', color='w', markerfacecolor='gray', 
                                       markeredgecolor='black', markersize=8, alpha=0.6, 
                                       label='Biological', linestyle='None'))
        if qc4_indices:
            legend_elements.append(Line2D([0], [0], marker='^', color='blue', markersize=8,
                                           markeredgecolor='black', markeredgewidth=0.5,
                                           label='QC4', linestyle='None'))
        if blauw_indices:
            legend_elements.append(Line2D([0], [0], marker='D', color='gold', markersize=8,
                                           markeredgecolor='black', markeredgewidth=0.5,
                                           label='blauw QC', linestyle='None'))
        
        ax.legend(handles=legend_elements, title="Batch / QC Type", loc='best', bbox_to_anchor=(1.05, 1), borderaxespad=0)
        
        fig.savefig(output_dir / f"{suffix}_all_samples_pca.png", dpi=300, bbox_inches='tight')
        plt.close(fig)
        
        # --- PCA for QC samples ONLY with filtered features ---
        # Filter to features present in >=80% of QC samples to remove gap-filled features
        qc_samples_for_filter = qc4_samples + blauw_samples
        if len(qc_samples_for_filter) >= 2:  # Need at least 2 QC samples
            qc_data_for_filter = df[qc_samples_for_filter]
            
            # Calculate percentage of QC samples where each feature is present (non-NaN)
            feature_presence = qc_data_for_filter.notna().mean(axis=1)
            
            # Filter: features present in >=80% of QC samples (more inclusive)
            high_presence_mask = feature_presence >= 0.80
            filtered_features = high_presence_mask[high_presence_mask].index
            
            if len(filtered_features) > 0:
                df_qc_filtered = df.loc[filtered_features, qc_samples_for_filter]
                
                # Handle NaN values
                if df_qc_filtered.isna().any().any():
                    min_positive = df_qc_filtered[df_qc_filtered > 0].min().min()
                    small_value = min_positive / 2 if not pd.isna(min_positive) else 1e-10
                    df_qc_filtered = df_qc_filtered.fillna(small_value)
                
                # Standardize and perform PCA
                scaler_qc = StandardScaler()
                df_qc_scaled = scaler_qc.fit_transform(df_qc_filtered.T)
                
                pca_qc = PCA(n_components=2, random_state=42)
                pca_qc_result = pca_qc.fit_transform(df_qc_scaled)
                
                # Create figure for QC-only PCA
                fig_qc, ax_qc = plt.subplots(figsize=(10, 8))
                
                # Plot each QC type with its bright color
                if qc4_samples:
                    qc4_idx = [qc_samples_for_filter.index(s) for s in qc4_samples if s in qc_samples_for_filter]
                    if qc4_idx:
                        ax_qc.scatter(
                            pca_qc_result[qc4_idx, 0],
                            pca_qc_result[qc4_idx, 1],
                            c='blue',
                            alpha=1.0,
                            s=100,
                            marker='^',
                            edgecolors='black',
                            linewidth=0.5,
                            label='QC4'
                        )
                
                if blauw_samples:
                    blauw_idx = [qc_samples_for_filter.index(s) for s in blauw_samples if s in qc_samples_for_filter]
                    if blauw_idx:
                        ax_qc.scatter(
                            pca_qc_result[blauw_idx, 0],
                            pca_qc_result[blauw_idx, 1],
                            c='gold',
                            alpha=1.0,
                            s=100,
                            marker='D',
                            edgecolors='black',
                            linewidth=0.5,
                            label='blauw QC'
                        )
                
                # Calculate explained variance
                explained_variance_qc = pca_qc.explained_variance_ratio_
                
                ax_qc.set_title(f"{label} (QC-only PCA, {len(filtered_features)} features in ≥80% QC)\nExplained Variance: PC1={explained_variance_qc[0]:.2%}, PC2={explained_variance_qc[1]:.2%}")
                ax_qc.set_xlabel(f"PC1 ({explained_variance_qc[0]:.1%})")
                ax_qc.set_ylabel(f"PC2 ({explained_variance_qc[1]:.1%})")
                ax_qc.grid(True, alpha=0.3)
                
                # Create legend
                from matplotlib.lines import Line2D
                qc_legend_elements = []
                if qc4_samples:
                    qc_legend_elements.append(Line2D([0], [0], marker='^', color='blue', markersize=8,
                                                       markeredgecolor='black', markeredgewidth=0.5,
                                                       label='QC4', linestyle='None'))
                if blauw_samples:
                    qc_legend_elements.append(Line2D([0], [0], marker='D', color='gold', markersize=8,
                                                       markeredgecolor='black', markeredgewidth=0.5,
                                                       label='blauw QC', linestyle='None'))
                
                if qc_legend_elements:
                    ax_qc.legend(handles=qc_legend_elements, title="QC Type", loc='best')
                
                fig_qc.savefig(output_dir / f"{suffix}_qc_filtered_pca.png", dpi=300, bbox_inches='tight')
                plt.close(fig_qc)
                
                print(f"  ✓ Saved QC-only PCA (filtered features) to {output_dir / f'{suffix}_qc_filtered_pca.png'}")


# =============================================================================
# Individual Visualization Functions (for modular use)
# =============================================================================

def plot_umap(
    data: pd.DataFrame,
    batch_vector: np.ndarray,
    output_path: Path,
    title: str = "UMAP",
    random_state: int = 42,
    figsize: Tuple[int, int] = (10, 8),
    dpi: int = 300,
) -> None:
    """
    Generate and save a UMAP plot.
    
    Args:
        data: Feature data (features x samples)
        batch_vector: Batch labels for each sample
        output_path: Path to save the plot
        title: Plot title (default: "UMAP")
        random_state: Random seed for reproducibility (default: 42)
        figsize: Figure size (default: (10, 8))
        dpi: DPI for saved image (default: 300)
    """
    # Handle NaN values
    if data.isna().any().any():
        min_positive = data[data > 0].min().min()
        small_value = min_positive / 2 if not pd.isna(min_positive) else 1e-10
        data = data.fillna(small_value)
    
    emb = umap.UMAP(random_state=random_state).fit_transform(data.T)
    fig, ax = plt.subplots(figsize=figsize)
    sns.scatterplot(x=emb[:, 0], y=emb[:, 1], hue=batch_vector, palette='viridis', ax=ax)
    ax.set_title(title)
    fig.savefig(output_path, dpi=dpi, bbox_inches='tight')
    plt.close(fig)


def plot_boxplot(
    data: pd.DataFrame,
    batch_vector: np.ndarray,
    output_path: Path,
    title: str = "Boxplot",
    figsize: Tuple[int, int] = (12, 6),
    dpi: int = 300,
) -> None:
    """
    Generate and save a boxplot of mean intensities by batch.
    
    Args:
        data: Feature data (features x samples)
        batch_vector: Batch labels for each sample
        output_path: Path to save the plot
        title: Plot title (default: "Boxplot")
        figsize: Figure size (default: (12, 6))
        dpi: DPI for saved image (default: 300)
    """
    unique_batches = np.unique(batch_vector)
    
    fig, ax = plt.subplots(figsize=figsize)
    sns.boxplot(x=batch_vector, y=data.T.mean(axis=1), palette='viridis', ax=ax, showfliers=False)
    ax.set_title(title)
    ax.set_xlabel('Batch')
    ax.set_ylabel('Mean Intensity per Sample')
    batch_labels = [f"Batch {b}" for b in sorted(unique_batches)]
    ax.set_xticklabels(batch_labels)
    fig.savefig(output_path, dpi=dpi, bbox_inches='tight')
    plt.close(fig)


def plot_rsd_distribution(
    data: pd.DataFrame,
    group_samples: List[str],
    output_path: Path,
    title: str = "RSD Distribution",
    xaxis_max: float = 50.0,
    figsize: Tuple[int, int] = (8, 4),
    dpi: int = 300,
) -> None:
    """
    Generate and save an RSD distribution plot for a QC group.
    
    Args:
        data: Feature data (features x samples)
        group_samples: List of sample names belonging to the QC group
        output_path: Path to save the plot
        title: Plot title (default: "RSD Distribution")
        xaxis_max: Maximum RSD value for x-axis (default: 50.0)
        figsize: Figure size (default: (8, 4))
        dpi: DPI for saved image (default: 300)
    """
    if not group_samples:
        return
    
    group_data = data[group_samples]
    group_means = group_data.mean(axis=1)
    group_stds = group_data.std(axis=1)
    rsd = (group_stds / group_means) * 100
    
    plt.figure(figsize=figsize)
    
    # Filter RSD values for plotting (keep within x-axis range for better visualization)
    rsd_filtered = rsd[rsd <= xaxis_max]
    num_outliers = (rsd > xaxis_max).sum()
    
    if len(rsd_filtered) == 0:
        # All values are outliers, show all data
        rsd_filtered = rsd
    
    # Use adaptive binning
    data_range = rsd_filtered.max() - rsd_filtered.min()
    if data_range > 0:
        num_bins = min(30, max(10, int(data_range * 2)))
    else:
        num_bins = 10
    
    sns.histplot(rsd_filtered, bins=num_bins, kde=True)
    plt.axvline(15, color='red', linestyle='--', label='RSD = 15%')
    plt.axvline(20, color='orange', linestyle='--', label='RSD = 20%')
    plt.title(title)
    plt.xlabel("RSD (%)")
    plt.ylabel("Number of Features")
    plt.legend()
    plt.grid(True)
    plt.xlim(0, xaxis_max)
    plt.savefig(output_path, dpi=dpi, bbox_inches='tight')
    plt.close()


def plot_qc_pca(
    data: pd.DataFrame,
    batch_dict: Dict[str, int],
    output_path: Path,
    title: str = "PCA of QC Samples",
    figsize: Tuple[int, int] = (10, 8),
    dpi: int = 300,
    n_components: int = 2,
) -> None:
    """
    Generate and save a PCA plot for QC4 and blauw QC samples.
    
    This function extracts QC4 and blauw QC samples from the data,
    performs PCA, and plots the results with batch labels as hue
    to verify that QC samples cluster properly after batch correction.
    
    Args:
        data: Feature data (features x samples)
        batch_dict: Dictionary mapping sample names to batch labels
        output_path: Path to save the plot
        title: Plot title (default: "PCA of QC Samples")
        figsize: Figure size (default: (10, 8))
        dpi: DPI for saved image (default: 300)
        n_components: Number of PCA components to compute (default: 2)
    """
    # Identify QC4 and blauw QC samples
    qc_samples = [col for col in data.columns if 'QC4' in col or 'blauw' in col]
    
    if not qc_samples:
        logger.warning("No QC4 or blauw QC samples found for PCA plot")
        return
    
    # Filter data to QC samples only
    qc_data = data[qc_samples]
    
    # Handle NaN values
    if qc_data.isna().any().any():
        min_positive = qc_data[qc_data > 0].min().min()
        small_value = min_positive / 2 if not pd.isna(min_positive) else 1e-10
        qc_data = qc_data.fillna(small_value)
    
    # Standardize the data (important for PCA)
    scaler = StandardScaler()
    qc_data_scaled = scaler.fit_transform(qc_data.T)
    
    # Perform PCA
    pca = PCA(n_components=n_components, random_state=42)
    pca_result = pca.fit_transform(qc_data_scaled)
    
    # Get batch labels for QC samples
    batch_labels = [batch_dict.get(col, 'Unknown') for col in qc_samples]
    batch_labels_str = [f"Batch {b}" for b in batch_labels]
    
    # Calculate explained variance
    explained_variance = pca.explained_variance_ratio_
    
    # Create plot
    fig, ax = plt.subplots(figsize=figsize)
    
    # Create a color palette based on unique batches
    unique_batches = sorted(set(batch_labels))
    palette = sns.color_palette('viridis', n_colors=len(unique_batches))
    
    # Map batch labels to colors
    batch_to_color = {b: palette[i] for i, b in enumerate(unique_batches)}
    colors = [batch_to_color.get(b, 'gray') for b in batch_labels]
    
    # Scatter plot
    scatter = ax.scatter(
        pca_result[:, 0],
        pca_result[:, 1],
        c=colors,
        alpha=0.7,
        s=60,
    )
    
    # Add sample labels for clarity
    for i, sample in enumerate(qc_samples):
        ax.text(
            pca_result[i, 0],
            pca_result[i, 1],
            sample,
            fontsize=8,
            ha='right',
            va='bottom',
        )
    
    ax.set_title(f"{title}\nExplained Variance: PC1={explained_variance[0]:.2%}, PC2={explained_variance[1]:.2%}")
    ax.set_xlabel(f"PC1 ({explained_variance[0]:.1%})")
    ax.set_ylabel(f"PC2 ({explained_variance[1]:.1%})")
    ax.grid(True, alpha=0.3)
    
    # Create legend
    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor=batch_to_color[b], label=f"Batch {b}")
        for b in sorted(unique_batches)
    ]
    ax.legend(handles=legend_elements, title="Batch")
    
    fig.savefig(output_path, dpi=dpi, bbox_inches='tight')
    plt.close(fig)
    
    logger.info(f"Saved QC PCA plot to {output_path}")
